#pragma config(Sensor, in1,    LeftPot,        sensorPotentiometer)
#pragma config(Sensor, in2,    RightPot,       sensorPotentiometer)
#pragma config(Sensor, in4,    Gyro,           sensorGyro)
#pragma config(Sensor, in5,    autonChoose,    sensorPotentiometer)
#pragma config(Sensor, in6,    CubeLimit,      sensorAnalog)
#pragma config(Sensor, dgtl1,  QuadEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  Turntable,      sensorDigitalOut)
#pragma config(Sensor, dgtl4,  Claw,           sensorDigitalOut)
#pragma config(Sensor, dgtl5,  BackLeftEnc,    sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  BackRightEnc,   sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  FrontRightEnc,  sensorQuadEncoder)
#pragma config(Sensor, dgtl11, FrontLeftEnc,   sensorQuadEncoder)
#pragma config(Motor,  port1,  CubeIntakeMotor2, tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,  FrontLeftLiftMotor, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,  FrontRightLiftMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,  frontRight,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,  backRight,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,  frontLeft,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,  backLeft,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port8,  BackLeftLiftMotor, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,  BackRightLiftMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10, CubeIntakeMotor, tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// Robot Code for Vex Skyrise 2014-2015
// Author: Joe Mattekatt

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

// Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

#include "utilities.c"
#include "drive.c"
#include "intake.c"
#include "lift.c"
#include "autonomous.c"

#define DEBUG
#define SHOW_BATTERY

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  bStopTasksBetweenModes = true;

  // Completely clear out any previous sensor readings by setting the port to "sensorNone"
  SensorType[in4] = sensorNone;
  wait1Msec(1000);

  // Reconfigure Analog Port 8 as a Gyro sensor and allow time for ROBOTC to calibrate it
  SensorType[in4] = sensorGyro;
  wait1Msec(2000);
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control the robot during the autonomous phase of    */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*---------------------------------------------------------------------------*/

task autonomous()
{
  // Use selection potentiometer to select approriate autonomous routine
  ChooseAutoRoutine();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control the robot during the user control phase of  */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
  // Toggle buttons initialize
  ToggleActuator clawToggle, turntableToggle;
  ToggleActuatorInit(clawToggle, Btn8D, Claw);
  ToggleActuatorInit(turntableToggle, Btn8U, Turntable);

  ToggleButton intakeToggle;
  ToggleButtonInit(intakeToggle, Btn8R);

  while (true)
  {
    // This is the main execution loop for the user control program.
    // Each time through the loop the program should update motor + actuator
    // values based on feedback from the joysticks.

    // Update Toggle button states
    ToggleActuatorUpdate(clawToggle);
    ToggleActuatorUpdate(turntableToggle);
    ToggleButtonUpdate(intakeToggle);

    // Control intake operation
    IntakeStateMachine(intakeToggle);

    // Lift operation using joystick controls
    JoystickLift();

    // Drive using joystick controls
    JoystickDrive();

    #ifdef SHOW_BATTERY
      DisplayBatteryLevels();
    #endif

    #ifdef DEBUG
      DisplayRow(1, "%d %t %d", SensorValue[LeftPot], SensorValue[RightPot]);
    #endif

    LOOP_DELAY;
  }
}
